# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: parallel_n64

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  ################################## CELLULAR ################################
  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-arm64.yml'

  # iOS (armv7)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios9.yml'

  ################################## CONSOLES ################################
    
  #################################### MISC ##################################

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    WITH_DYNAREC: x86_64
    HAVE_THR_AL: 1
    HAVE_PARALLEL: 1
    HAVE_PARALLEL_RSP: 1

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  variables:
    WITH_DYNAREC: x86
    HAVE_THR_AL: 1
    HAVE_PARALLEL: 1
    HAVE_PARALLEL_RSP: 1
    
# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
  variables:
    WITH_DYNAREC: x86_64
    HAVE_THR_AL: 1
    HAVE_PARALLEL: 1
    HAVE_PARALLEL_RSP: 1

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .core-defs
    - .libretro-linux-i686-make-default
  variables:
    WITH_DYNAREC: i686
    HAVE_THR_AL: 1
    HAVE_PARALLEL: 1
    HAVE_PARALLEL_RSP: 1

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs

################################### CELLULAR #################################
# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-arm64-make-default
    - .core-defs

# iOS (armv7) [iOS 9 and up]
libretro-build-ios9:
  extends:
    - .libretro-ios9-make-default
    - .core-defs
